### ISSUE TITLE
Broken Different World for Courses

### ISSUE THREAD

**Issue by Acult** [A5H73Y/Parkour#154]
```
Courses:
- test
test:
  Creator: acult
  Views: 8
  Completed: 0
  XP: 0
  Points: 0
  World: DIM100
  '0':
    X: -233607.5
    Y: 63.5
    Z: -2991.5
    Yaw: -212.72424
    Pitch: 16.349932
  Prize:
    Material: DIAMOND
    Amount: 1
```

The plugin doesn't recognize "DIM100" as world when put inside courses, so by that it teleports to the overworld and not to DIM100.
Instead, the lobby at DIM100 works fine.

Any fix?
