### ISSUE TITLE
Couple questions/feature requests

### ISSUE THREAD

**Issue by LogGits** [A5H73Y/Parkour#157]
Is it possible to:
1) Run commands on the players first time completing a certain course
2) Run seperate commands on every other completion of a certain course

**Comment by steve4744** [comment]
1. Yes - run `/pa prize [course]` and set a command reward for the course. Then run `/pa rewardonce [course]` so that it is only given to a player once.

https://a5h73y.github.io/Parkour/part6.html

2. The prize(s) for the course is either enabIed or disabled, so I don't think this is currently possible.

**Comment by LogGits** [comment]
Regarding the second one, is it possible to do for example:
```yaml
First time:
- 32 diamonds
- 3 commands (/money give, etc)
Other times:
- 1 diamond
- 1 command (/xp give %PLAYER% 300}
```
