### ISSUE TITLE
Bugs with Parkour Scoreboard

### ISSUE THREAD

**Issue by DrakePork** [A5H73Y/Parkour#179]
When players join parkour this error appears, and they don't get a scoreboard.
https://pastebin.com/xzwKfQyq

Also, before this bug began,  current time wasn't displayed on the scoreboard, even though its enabled in the config.
```
Scoreboard:
  Enabled: true
  Display:
    CourseName: true
    BestTimeEver: true
    BestTimeEverName: true
    BestTimeByMe: true
    CurrentTime: true
  MainHeading: '&b&l== Parkour =='
  TitleFormat: '&b%TITLE%'
  TextFormat: '&f%TEXT%'
```
