### ISSUE TITLE
Per Course Messages

### ISSUE THREAD

**Issue by LogGits** [A5H73Y/Parkour#226]
I'd like to add a theme each of my parkour maps. Actions that would be nice to see have messages:
```yaml
Parkour:
    Start: 'Get to the end of the map to win a prize!'
    Leave: 'Better luck next time.'
    Finish: 'Congratulations, you found the gem!'
    Checkpoints:
        '1': 'Nice work, you have reached the temple checkpoint, careful the trees get pretty high.'
        '2': 'Great work completing the temple checkpoint, stay clear of ..."
```
This type of system whereby if the message isn't there it just doesn't send a message, would be extremely helpful in developing immersive courses. This feature would need to be configurable for each parkour map.
