### ISSUE TITLE
DefaultPrize is rewarded in addition to the economy payout, even with prize set to false.

### ISSUE THREAD

**Issue by mibby** [A5H73Y/Parkour#30]
Compiled as of https://github.com/A5H73Y/Parkour/commit/bc5ff346cbb5f3240195612e31f1b8d031ada8f5

The DefaultPrize in the main config is rewarding on parkour course completion in addition to economy payout defined. Would it be possible to only reward in-game currency for the course?

```
  Prize:
    Enabled: true
  DefaultPrize:
    Material: DIAMOND
    Amount: 1
    XP: 0
```

```
Price:
  Kit: 0
  spawn:
    Finish: 25
```

Setting the following only disables the economy payout, not the diamond reward.
```
  Prize:
    Enabled: false
```
