### ISSUE TITLE
Parkour reload does not reload the economy.yml.

### ISSUE THREAD

**Issue by mibby** [A5H73Y/Parkour#33]
I originally had this set for my parkour course.
```
Price:
  Kit: 0
  spawn:
    Finish: 10
```

I manually changed the value to $25.
```
Price:
  Kit: 0
  spawn:
    Finish: 25
```

Then reloaded the parkour plugin with ```/parkour reload```. Completing the course again, it outputted in chat that I was rewarded $10.
