### ISSUE TITLE
Bedrock users do not get teleported out of a course with /pa leave

### ISSUE THREAD

**Issue by c0wg0d** [A5H73Y/Parkour#366]
If Bedrock users use the /pa leave command or Shift + Right Click with the fern, they do "exit" the course, but they do not get teleported back out to the lobby.  This does not happen with Java users.

My OnLeave config is the following:

```yaml
OnLeave:
  TeleportAway: true
  DestroyCourseProgress: true
  TeleportToLinkedLobby: true
  GiveGainedItemsBack: false
  RetainResumableInventory: false
```

This server is running Paper version 1.21.3-83-ver/1.21.3@d6c81da (2025-03-28T15:57:09Z) (Implementing API version 1.21.3-R0.1-SNAPSHOT)

Using Parkour 7.2.4.
