### ISSUE TITLE
Linked lobbies aren't being used - default lobby set is overriding.

### ISSUE THREAD

**Issue by mibby** [A5H73Y/Parkour#38]
Compiled as of https://github.com/A5H73Y/Parkour/commit/d3cbb66f46a7bfcc1755b11293a3769b999f9f7d

On exit when playing in courses with a linked lobby, it is taking players to the default lobby location instead of the set linked one.

Edit: It seems custom lounges don't work whatsoever outright. Removing the default lounge location, it just spams that no lounge has been setup despite a custom one existing and being linked to a course. With a default location set in addition to a custom location set / linked, it always uses the default location.

```
Lobby:
  Set: true
  World: world
  X: -6287.321349023397
  Y: 125.0
  Z: 2116.5467648669683
  Pitch: 2.9999778
  Yaw: -90.3022
  parkour:
    World: world
    X: -11380.5
    Y: 107.0
    Z: 10961.5
    Pitch: -0.15001002
    Yaw: -90.08281
```

```
Courses:
- spawn
- parkour1
- parkour2
- parkour3
- parkour4
- parkour5
- parkour6
- parkour7
- parkour8
- parkour9
- parkour10
- parkour11
- parkour12
- parkour13
- parkour14
- parkour15
- parkour16
- parkour17
- parkour18
- parkour19
- parkour20
- parkour21
- parkour22
- parkour23
- parkour24
- parkour25
spawn:
  Creator: player
  Views: 1258
  Completed: 59
  XP: 0
  Points: 0
  World: world
  '0':
    X: -6293.703158744823
    Y: 126.0
    Z: 2115.380310594939
    Yaw: 109.047844
    Pitch: 6.449876
  Finished: true
parkour1:
  Creator: player
  Views: 3
  Completed: 0
  XP: 0
  Points: 0
  World: world
  '0':
    X: -11428.5
    Y: 151.5
    Z: 10900.5
    Yaw: -90.68261
    Pitch: 1.0499918
  LinkedLobby: parkour
parkour2:
  Creator: player
  Views: 0
  Completed: 0
  XP: 0
  Points: 0
  World: world
  '0':
    X: -11428.5
    Y: 151.5
    Z: 10941.5
    Yaw: -90.83276
    Pitch: -0.29999185
  LinkedLobby: parkour
```

**Comment by steve4744** [comment]
This came up during testing I did, and is by design.  
Currently, if you exit a course without completing it, then you are sent back to the default lobby (which must exist).
If you complete the course only then do you progress to the linked lobby.
That's the logic but I think it was under review as to whether it should be configurable.

**Comment by mibby** [comment]
What's the point of setting a custom lobby for a specific course if that lobby isn't going to be used on exit? Seems a bit redundant.

**Comment by A5H73Y** [comment]
Sure, you've both raised this and as Steve mentioned I was going to make this configurable but didn't get around to it.. I will add this in my next commit.
The theory when I had a Parkour server than someone would get 'promoted' to the custom lobby only once they'd completed the course required to join it. If you joined a 'hard' course and failed, you wouldn't want them to have the satisfaction of joining a hard lobby. (It made more sense in my head at the time)

**Comment by mibby** [comment]
@A5H73Y 
With this set to true, it outputs 'lobby does not exist' when using the exit tool in a course that does not have a custom lobby set.

```
OnLeave:
  TeleportToCustomLobby: true
```

```
Lobby:
  Set: true
  World: world
  X: -6287.5
  Y: 125.0
  Z: 2116.5
  Pitch: -1.0501239
  Yaw: -90.002174
```

Could you add a check to use the default lobby location if a specified one doesn't exist?
