### ISSUE TITLE
The create kit conversation is not initialising strength and duration for subsequent blocks

### ISSUE THREAD

**Issue by steve4744** [A5H73Y/Parkour#72]
Running the '/pa createkit' conversation, once 'strength' and 'duration' have been specified for one block, the values are carried forward to any subsequent blocks that don't require them, e.g. 

``` 
test_kit:
    SPONGE:
      Action: bounce
      Strength: 5
      Duration: 40
    DIAMOND_BLOCK:
      Action: finish
      Strength: 5
      Duration: 40
    GRASS:
      Action: death
      Strength: 5
      Duration: 40
```
